CREATE DATABASE CONSULTORIO

USE CONSULTORIO

CREATE TABLE PACIENTE
(
	DNI_PA CHAR(8) PRIMARY KEY NOT NULL,
	NOM_PA VARCHAR(40)NOT NULL,
	APE_PA VARCHAR(40)NOT NULL,
	TEL_PA VARCHAR(9)NOT NULL,
)

CREATE TABLE ESPECIALIDAD
(
	ID_ESP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOM_ESP VARCHAR(50)NOT NULL, 
)

CREATE TABLE DOCTOR
(
	DNI_DOC CHAR(8) PRIMARY KEY NOT NULL,
	NOM_DOC VARCHAR(40)NOT NULL,
	APE_DOC VARCHAR(40)NOT NULL,
	TEL_DOC VARCHAR(9)NOT NULL,
	ESP_ID INT NOT NULL,
)

CREATE TABLE RESERVACION
(
	ID_RES INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	PA_DNI CHAR(8) NOT NULL,
	DOC_DNI CHAR(8) NOT NULL,
	FECH_RES DATE NOT NULL,
	HOR_RES TIME NOT NULL,
	MOTI_RES VARCHAR(100) NOT NULL,
)

ALTER TABLE DOCTOR ADD FOREIGN KEY (ESP_ID) REFERENCES ESPECIALIDAD (ID_ESP)

ALTER TABLE RESERVACION ADD FOREIGN KEY (PA_DNI) REFERENCES PACIENTE (DNI_PA)
ALTER TABLE RESERVACION ADD FOREIGN KEY (DOC_DNI) REFERENCES DOCTOR (DNI_DOC)

-----Insertar datos------
INSERT INTO PACIENTE VALUES ('76307332','LUIS','ARENAS DE LA TORRE','993018815')
INSERT INTO PACIENTE VALUES ('76324843','JOSE','MARTINEZ GLORIA','994075577')
INSERT INTO PACIENTE VALUES ('76303646','ANA LISA','ESPINOSA URBANO','949797300')
INSERT INTO PACIENTE VALUES ('76316972','JAIME','FLOREZ PEREZ','999902644')
INSERT INTO PACIENTE VALUES ('76306235','JESUS ANTONIO',' GONZALEZ JIMENEZ','997351889')

INSERT INTO DOCTOR VALUES ('50715968','CLAUDIA EDDY','GOMEZ ACOSTA','949666212','1')
INSERT INTO DOCTOR VALUES ('68635251','JOSE ESTEBAN',' GUERRERO DE TEJADA','965323138','4')
INSERT INTO DOCTOR VALUES ('72084710','AUGUSTO','HIDALGO OTERO','989654339','2')
INSERT INTO DOCTOR VALUES ('95681730','SAULO','LOAIZA MOTATO','973802391','5')
INSERT INTO DOCTOR VALUES ('72368874','WILLIAM','PEREZ DORADO','952268315','3')

INSERT INTO ESPECIALIDAD VALUES ('NUTRICION')
INSERT INTO ESPECIALIDAD VALUES ('NEUROLOGIA')
INSERT INTO ESPECIALIDAD VALUES ('CARDIOLOGIA')
INSERT INTO ESPECIALIDAD VALUES ('MEDICINA GENERAL')
INSERT INTO ESPECIALIDAD VALUES ('ODONTOLOGIA')
INSERT INTO ESPECIALIDAD VALUES ('NEUMOLOGIA')

INSERT INTO RESERVACION VALUES ('76303646','72368874','16/07/2022','9:00','DOLOR EN EL PECHO')


---Lista de Pacientes---
IF OBJECT_ID('SP_LISTAPACIENTE')IS NOT NULL
DROP PROC SP_LISTAPACIENTE
GO
CREATE PROC SP_LISTAPACIENTE
AS
SELECT P.DNI_PA AS DNI,
		P.NOM_PA AS NOMBRES,
		P.APE_PA AS APELLIDOS,
		P.TEL_PA AS TELEFONO
		FROM PACIENTE P

EXECUTE SP_LISTAPACIENTE


---Nuevo Paciente-----
IF OBJECT_ID('SP_NUEVOPACIENTE')IS NOT NULL
DROP PROC SP_NUEVOPACIENTE
GO
CREATE PROC SP_NUEVOPACIENTE(@DNI CHAR(8),@NOM VARCHAR(40),@APE VARCHAR(40),@TEL VARCHAR(9))
AS
INSERT INTO PACIENTE VALUES (@DNI,@NOM,@APE,@TEL)

EXECUTE SP_NUEVOPACIENTE '83829184','BRANDON DANIEL','TORRES DEL AGUILA','921782702'


---Modificar paciente---
IF OBJECT_ID('SP_MODIFICAPACIENTE')IS NOT NULL
DROP PROC SP_MODIFICAPACIENTE
GO
CREATE PROC SP_MODIFICAPACIENTE(@DNI CHAR(8),@NOM VARCHAR(40),@APE VARCHAR(40),@TEL VARCHAR(9))
AS
UPDATE PACIENTE
SET NOM_PA=@NOM,APE_PA=@APE,TEL_PA=@TEL WHERE DNI_PA=@DNI

EXECUTE SP_MODIFICAPACIENTE '83829184','BRANDON DANIEL','TORRES DEL AGUILA','921782702'


---Eliminar paciente
IF OBJECT_ID('SP_ELIMINARPACIENTE')IS NOT NULL
DROP PROC SP_ELIMINARPACIENTE
GO
CREATE PROC SP_ELIMINARPACIENTE(@DNI CHAR(8))
AS
DELETE PACIENTE WHERE DNI_PA=@DNI
DELETE RESERVACION WHERE PA_DNI=@DNI

EXECUTE SP_ELIMINARPACIENTE '83829184'


---Buscar paciente---
IF OBJECT_ID('SP_BUSCARPACIENTE')IS NOT NULL
DROP PROC SP_BUSCARPACIENTE
GO
CREATE PROC SP_BUSCARPACIENTE(@DNI CHAR(8))
AS
SELECT P.DNI_PA AS DNI,
		P.NOM_PA AS NOMBRES,
		P.APE_PA AS APELLIDOS,
		P.TEL_PA AS TELEFONO
		FROM PACIENTE P
		WHERE DNI_PA=@DNI

EXECUTE SP_BUSCARPACIENTE '73906692'


---Lista de doctores---
IF OBJECT_ID('SP_LISTADOCTOR')IS NOT NULL
DROP PROC SP_LISTADOCTOR
GO
CREATE PROC SP_LISTADOCTOR
AS
SELECT D.DNI_DOC AS DNI,
		D.NOM_DOC AS NOMBRES,
		D.APE_DOC AS APELLIDOS,
		D.TEL_DOC AS TELEFONO,
		E.NOM_ESP AS ESPECIALIDAD
		FROM DOCTOR D
		JOIN ESPECIALIDAD E ON D.ESP_ID = E.ID_ESP

EXECUTE SP_LISTADOCTOR


---Nuevo doctor-----
IF OBJECT_ID('SP_NUEVODOCTOR')IS NOT NULL
DROP PROC SP_NUEVODOCTOR
GO
CREATE PROC SP_NUEVODOCTOR(@DNI CHAR(8),@NOM VARCHAR(40),@APE VARCHAR(40),@TEL VARCHAR(9),@ID_ESP INT)
AS
INSERT INTO DOCTOR VALUES (@DNI,@NOM,@APE,@TEL,@ID_ESP)

EXECUTE SP_NUEVODOCTOR '81221243','SAN PEDRO','JUANEZ INCA','999172126','6'


---Modificar doctor---
IF OBJECT_ID('SP_MODIFICADOCTOR')IS NOT NULL
DROP PROC SP_MODIFICADOCTOR
GO
CREATE PROC SP_MODIFICADOCTOR(@DNI CHAR(8),@NOM VARCHAR(40),@APE VARCHAR(40),@TEL VARCHAR(9))
AS
UPDATE DOCTOR
SET NOM_DOC=@NOM,APE_DOC=@APE,TEL_DOC=@TEL WHERE DNI_DOC=@DNI

EXECUTE SP_MODIFICADOCTOR '95681730','SAULO','LOAIZA MOTATO','9724812391'


---Eliminar doctor-------
IF OBJECT_ID('SP_ELIMINARDOCTOR')IS NOT NULL
DROP PROC SP_ELIMINARDOCTOR
GO
CREATE PROC SP_ELIMINARDOCTOR(@DNI CHAR(8))
AS
DELETE DOCTOR WHERE DNI_DOC= @DNI
DELETE RESERVACION WHERE DOC_DNI= @DNI

EXECUTE SP_ELIMINARDOCTOR '81221243'

---Buscar doctor---
IF OBJECT_ID('SP_BUSCARDOCTOR')IS NOT NULL
DROP PROC SP_BUSCARDOCTOR
GO
CREATE PROC SP_BUSCARDOCTOR(@DNI CHAR(8))
AS
SELECT D.DNI_DOC AS DNI,
		D.NOM_DOC AS NOMBRES,
		D.APE_DOC AS APELLIDOS,
		D.TEL_DOC AS TELEFONO,
		E.NOM_ESP AS ESPECIALIDAD
		FROM DOCTOR D
		JOIN ESPECIALIDAD E ON D.ESP_ID = E.ID_ESP
		WHERE DNI_DOC=@DNI

EXECUTE SP_BUSCARDOCTOR'72368874'

---Lista reserva---
IF OBJECT_ID('SP_LISTARESERVA')IS NOT NULL
DROP PROC SP_LISTARESERVA
GO
CREATE PROC SP_LISTARESERVA
AS
SELECT R.ID_RES AS ID,  
		P.DNI_PA AS DNI_PACIENTE,
		P.NOM_PA AS NOMBRE_PACIENTE,
		P.APE_PA AS APELLIDO_PACIENTE,
		D.DNI_DOC AS DNI_DOCTOR,
		D.NOM_DOC AS NOMBRE_DOCTOR,
		D.APE_DOC AS APELLIDO_DOCTOR,
		R.FECH_RES AS FECHA,
		R.HOR_RES AS HORA,
		R.MOTI_RES AS MOTIVO
		FROM RESERVACION R
		JOIN PACIENTE P ON R.PA_DNI = P.DNI_PA
		JOIN DOCTOR D ON R.DOC_DNI = D.DNI_DOC 

EXECUTE SP_LISTARESERVA

---Nueva Reserva
IF OBJECT_ID('SP_NUEVARESERVA')IS NOT NULL
DROP PROC SP_NUEVARESERVA
GO
CREATE PROC SP_NUEVARESERVA(@DNI_PACI CHAR(8),@DNI_DOCT CHAR(8),@FECH DATE,@HORA TIME,@MOT VARCHAR(100))
AS
INSERT INTO RESERVACION VALUES (@DNI_PACI,@DNI_DOCT,@FECH,@HORA,@MOT)

EXECUTE SP_NUEVARESERVA '73906692','68635251','16/06/2022','08:00','CONSULTA' 

---Busca reserva---
IF OBJECT_ID('SP_BUSCARESERVA')IS NOT NULL
DROP PROC SP_BUSCARESERVA
GO
CREATE PROC SP_BUSCARESERVA(@ID INT,@DNI_PAC CHAR(8))
AS
SELECT R.ID_RES AS ID, 
		P.DNI_PA AS DNI_PACIENTE,
		P.NOM_PA AS NOMBRE_PACIENTE,
		P.APE_PA AS APELLIDO_PACIENTE,
		D.DNI_DOC AS DNI_DOCTOR,
		D.NOM_DOC AS NOMBRE_DOCTOR,
		D.APE_DOC AS APELLIDO_DOCTOR,
		R.FECH_RES AS FECHA,
		R.HOR_RES AS HORA,
		R.MOTI_RES AS MOTIVO
		FROM RESERVACION R
		JOIN PACIENTE P ON R.PA_DNI = P.DNI_PA
		JOIN DOCTOR D ON R.DOC_DNI = D.DNI_DOC
		WHERE ID_RES=@ID OR DNI_PA=@DNI_PAC

EXECUTE SP_BUSCARESERVA '','73906692'

---Modifica reserva---
IF OBJECT_ID('SP_MODIFICARESERVA')IS NOT NULL
DROP PROC SP_MODIFICARESERVA
GO
CREATE PROC SP_MODIFICARESERVA(@ID INT,@DNI_DOC CHAR(8),@FECH DATE,@HOR TIME,@MOTI VARCHAR(100))
AS
UPDATE RESERVACION
SET DOC_DNI=@DNI_DOC,FECH_RES=@FECH,HOR_RES=@HOR,MOTI_RES=@MOTI WHERE ID_RES=@ID

EXECUTE SP_MODIFICARESERVA '5','68635251','17/06/2022','15:00','CONSULTA'

---Eliminar reserva---
IF OBJECT_ID('SP_ELIMINARESERVA')IS NOT NULL
DROP PROC SP_ELIMINARESERVA
GO
CREATE PROC SP_ELIMINARESERVA(@ID INT)
AS
DELETE RESERVACION WHERE ID_RES= @ID


EXECUTE SP_ELIMINARESERVA '1005'

---Mostrar doctor---
IF OBJECT_ID('SP_DOCTOR')IS NOT NULL
DROP PROC SP_DOCTOR
GO
CREATE PROC SP_DOCTOR
AS
SELECT D.DNI_DOC AS DNI,
		D.APE_DOC AS APELLIDO
		FROM DOCTOR D

EXECUTE SP_DOCTOR

---Lista especialidad---
IF OBJECT_ID('SP_LISTAESPECIALIDAD')IS NOT NULL
DROP PROC SP_LISTAESPECIALIDAD
GO
CREATE PROC SP_LISTAESPECIALIDAD
AS
SELECT E.ID_ESP AS ID,  
		E.NOM_ESP AS ESPECIALIDAD
		FROM ESPECIALIDAD E

EXECUTE SP_LISTAESPECIALIDAD

---Buscar especialidad
IF OBJECT_ID('SP_BUSCAESPECIALIDAD')IS NOT NULL
DROP PROC SP_BUSCAESPECIALIDAD
GO
CREATE PROC SP_BUSCAESPECIALIDAD(@ID INT,@NOM VARCHAR(50))
AS
SELECT E.ID_ESP AS ID, 
		E.NOM_ESP AS ESPECIALIDAD
		FROM ESPECIALIDAD E
		WHERE ID_ESP=@ID OR NOM_ESP=@NOM

EXECUTE SP_BUSCAESPECIALIDAD '1',''


---Nueva especialidad---
IF OBJECT_ID('SP_NUEVAESPECIALIDAD')IS NOT NULL
DROP PROC SP_NUEVAESPECIALIDAD
GO
CREATE PROC SP_NUEVAESPECIALIDAD(@NOM VARCHAR(50))
AS
INSERT INTO ESPECIALIDAD VALUES (@NOM)

EXECUTE SP_NUEVAESPECIALIDAD 'ODONTOLOGIA'

---Modifica especialidad---
IF OBJECT_ID('SP_MODIFICARESPECIALIDAD')IS NOT NULL
DROP PROC SP_MODIFICARESPECIALIDAD
GO
CREATE PROC SP_MODIFICARESPECIALIDAD(@ID INT,@NOM VARCHAR(50))
AS
UPDATE ESPECIALIDAD
SET NOM_ESP=@NOM WHERE ID_ESP=@ID

EXECUTE SP_MODIFICARESPECIALIDAD '7','PEDIATRIA'